# Travis-CI for koreader-sync-server
# see travis-ci.org for details

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install redis-server openssl perl
    - sudo mkdir -p /etc/nginx/ssl
    - sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt -subj "/"

    - sudo apt-get install libreadline-dev libncurses5-dev libpcre3-dev libssl-dev
    - wget http://openresty.org/download/ngx_openresty-1.7.10.1.tar.gz
    - tar zxvf ngx_openresty-1.7.10.1.tar.gz
    - cd ngx_openresty-1.7.10.1/
    - ./configure && make && sudo make install && cd ..

    - sudo apt-get install luarocks
    - sudo luarocks install luasec
    - sudo luarocks install --server=http://gin.io/repo gin
    - sudo luarocks install busted

script:
    - redis-server &
    - sleep 3
    - busted

